### ISSUE TITLE
Black Screen Flash

### ISSUE THREAD

**Issue by ipkpjersi** [RS117/RLHD#199]
**Describe the bug**
Sometimes when loading a new region, or even a few seconds after loading a region (I think? maybe it happens more randomly than that), the screen will flicker. This bug has been going on for quite a few months, possibly even since launch of this plugin. I am using Linux but this bug also happens on Windows for my friend. Also, this issue is NOT present on the GPU plugin or software/CPU rendering.

**To Reproduce**
1. Run along Edgeville ditch
2. After enough regions load, you will see the screen flash black during or slightly after region load or even randomly without region loading.

**Expected behavior**
I expect the screen to not flash.

**Screenshots**
There is a video of this bug available here: https://streamable.com/sjhgz6 at 1:30 in the video you can definitely see the black screen flash, it looks like you can also see it at 0:15 in the same video without any region loading.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - RuneLite version: 1.8.7.1
 - Launcher version: 1.6.2
 - HD version: 1.0.11
 - GPU: NVIDIA GTX 1070
 - GPU Driver: 470.86

**Comment by sosodev** [comment]
Can you confirm if you're still experiencing this issue?

**Comment by ipkpjersi** [comment]
Yeah, I am still experiencing the issue. 

I noticed this time in the latest recording of it, there's a single "red" looking frame almost: https://i.imgur.com/QU4Kted.png

It happened right when loading a new region but doesn't always happen when loading a region, it happens randomly making me think it's maybe a race condition.

I did notice in the streamable recording, it's a single "red" frame as well: https://i.imgur.com/gjM7NUk.png

I'm not sure if this helps but maybe it's good information at least.

**Comment by sosodev** [comment]
This should be fixed as of the latest update

**Comment by ipkpjersi** [comment]
Hi,

I think this should be re-opened. This still happens as of 1.1.1: 
https://streamable.com/h2wxft
![](https://i.imgur.com/P6k3CSJ.png)
![](https://i.imgur.com/LXJt1CZ.png)

Cheers.

**Comment by aHooder** [comment]
Since this was a bit tricky to spot imo, here's 0:44 frame by frame:

https://user-images.githubusercontent.com/831317/167315762-20db5c10-ebdb-4f82-ab69-e5decad707e3.mp4
